stages:
  - test
  - flatpak

variables:
  RUST_BACKTRACE: "1"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .flatpak-builder/cache
    - .flatpak-builder/downloads

.flatpak-setup:
  image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
  before_script:
    - flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    - >
      flatpak install -y --noninteractive flathub
      org.freedesktop.Sdk//25.08
      org.freedesktop.Sdk.Extension.rust-stable//25.08

flatpak-test:
  extends: .flatpak-setup
  stage: test
  script:
    - >
      flatpak-builder --force-clean --disable-rofiles-fuse
      --build-only build-dir
      io.gitlab.lewisHeart.GnomePaths.json
    - >
      flatpak-builder --disable-rofiles-fuse
      --run build-dir
      io.gitlab.lewisHeart.GnomePaths.json
      cargo test

flatpak-bundle:
  extends: .flatpak-setup
  stage: flatpak
  script:
    - >
      flatpak-builder --force-clean --disable-rofiles-fuse
      --repo=repo build-dir
      io.gitlab.lewisHeart.GnomePaths.json
    - >
      flatpak build-bundle repo
      io.gitlab.lewisHeart.GnomePaths.flatpak
      io.gitlab.lewisHeart.GnomePaths
  artifacts:
    name: "io.gitlab.lewisHeart.GnomePaths-$CI_COMMIT_REF_NAME"
    paths:
      - io.gitlab.lewisHeart.GnomePaths.flatpak
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH